[package]
name = "test-ui"
version = "0.1.0"
authors = ["AsriFox"]
edition = "2021"
build = "build.rs"

[dependencies]
gtk = { package = "gtk4", version = "*" }
adw = { package = "libadwaita", version = "*" }
glib = "*"

[build-dependencies]
adw = { package = "libadwaita", version = "*" }